version: 2
updates:
  - package-ecosystem: npm
    directory: /wongsakorn127-byjaimesjames
    schedule:
      interval: weekly
      day: monday
      time: "03:00"
      timezone: Asia/Bangkok
    open-pull-requests-limit: 5
    groups:
      angular:
        patterns:
          - "@angular/*"
      firebase:
        patterns:
          - "firebase"
          - "@angular/fire"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "03:30"
      timezone: Asia/Bangkok
    open-pull-requests-limit: 5
